name: generate GitHub Profile Metrics
on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  # don't forget to change if you're using 'master' branch
  push:
    branches:
    - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    - name: Default metrics
      uses: lowlighter/metrics@latest
      with:
        filename: profile-metrics-output/metrics.base.svg
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        base: header, activity, community, repositories, metadata
    - name: Most used (with details)
      uses: lowlighter/metrics@latest
      with:
        filename: profile-metrics-output/details.svg
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        base: ""
        repositories_skipped: chatbot-ui, gitHub-readme-stats-clone, PL0-compiler
        plugin_languages: yes
        plugin_languages_ignored: >-
          tex, less, qmake, lex, gnuplot
        plugin_languages_details: bytes-size, percentage
        plugin_languages_limit: 8
        plugin_followup: yes
        plugin_followup_indepth: yes
    - name: Coding Habits Metrics
      uses: lowlighter/metrics@latest
      with:
        filename: profile-metrics-output/metrics.plugin.habits.svg
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes        # 興味深い事実を表示
        plugin_habits_charts: yes       # アクティビティチャートを表示
        plugin_habits_trim: yes         # 未使用の時間を省略
        plugin_habits_days: 14          # 過去14日分のデータを分析
        plugin_habits_languages_limit: 8 # 表示する言語数の制限
        plugin_habits_languages_threshold: "2%"  # 表示する言語の最小使用率
        config_timezone: Asia/Tokyo     # タイムゾーンを設定

    - name: Anilist Metrics
      uses: lowlighter/metrics@latest
      with:
        filename: profile-metrics-output/metrics.plugin.anilist.svg
        token: NOT_NEEDED
        base: ""
        plugin_anilist: yes
        plugin_anilist_user: RairuDev    # あなたのAniListのユーザー名に変更してください
        plugin_anilist_medias: anime, manga
        plugin_anilist_sections: favorites, watching, reading
        plugin_anilist_limit: 10           # 表示するアニメ/マンガの数
        plugin_anilist_limit_characters: 10  # 表示するキャラクターの数
        plugin_anilist_shuffle: yes      # 表示をシャッフル
